### ISSUE TITLE
change wallpapers (some of them, idk what it depends on) causes page to crush temporarily

### ISSUE THREAD

**Issue by snakeout96** [Raptor1818/RaptorOS#9]
need to fix rn, test yourself so far the site is down
seems to be a server issue rather than a script issue
here's a proof:
![image](https://github.com/user-attachments/assets/8b431365-05bb-4c79-a934-153ac6da8e62)

plus, _**as long as it doesn't conflict with your stylistic choices**_, pls prevent users from selecting text in the wallpaper imgs section

**Comment by Raptor1818** [comment]
Should be fixed. Next.js was complaining about not having `sharp` for image optimization.
Thanks, the fix should be deployed shortly, and if it happens again and I don't notice it please open another issue.
I will pick up this project again, and will fix the text selection.
